# sorting 
iloc: 인덱스(숫자)
loc: 열이름으로

In [1]:
import pandas as pd
movies = pd.read_csv('http://bit.ly/imdbratings')
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [3]:
#title columns만 sorting(오름차순)
movies.title.sort_values() 
#movies['title'].sort_values()

542     (500) Days of Summer
5               12 Angry Men
201         12 Years a Slave
698                127 Hours
110    2001: A Space Odyssey
               ...
955         Zero Dark Thirty
677                   Zodiac
615               Zombieland
526                     Zulu
864                    [Rec]
Name: title, Length: 979, dtype: object

In [4]:
movies.title.sort_values(ascending=False)#내림차순으로 sorting

864                    [Rec]
526                     Zulu
615               Zombieland
677                   Zodiac
955         Zero Dark Thirty
               ...
110    2001: A Space Odyssey
698                127 Hours
201         12 Years a Slave
5               12 Angry Men
542     (500) Days of Summer
Name: title, Length: 979, dtype: object

In [5]:
# nothing changed /  inplace 필요(원본은 갱신되지 않음)
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [6]:
movies.sort_values(['content_rating', 'duration']).head() #columns 두개 sorting 가능함

,star_rating,title,content_rating,genre,duration,actors_list
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
272,8.1,The Killing,APPROVED,Crime,85,"[u'Sterling Hayden', u'Coleen Gray', u'Vince E..."
703,7.6,Dracula,APPROVED,Horror,85,"[u'Bela Lugosi', u'Helen Chandler', u'David Ma..."
612,7.7,A Hard Day's Night,APPROVED,Comedy,87,"[u'John Lennon', u'Paul McCartney', u'George H..."

In [ ]:
# filter rows by column value
# 상영 시간이 200분이상인 영화 목록 정보를 보여라(duration>200)

In [7]:
booleans = []
for length in movies.duration:
    if length >= 200:
        booleans.append(True)
    else:
        booleans.append(False)
booleans[0:5]

[False, False, True, False, False]

In [8]:
is_long = pd.Series(booleans)  # series로 변환
is_long.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [9]:
movies[is_long].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."

In [10]:
# for loop 없이
is_long = movies.duration >= 200 # series operation의 output은 series
is_long.head()
#movies[movies.duration >= 200] 더짧게

0    False
1    False
2     True
3    False
4    False
Name: duration, dtype: bool

In [11]:
movies[is_long].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."

In [12]:
movies.loc[[0,1,2], :] # 0,1,2 행, 전체 열
# movies.loc[[0:2], :] # same
# movies.loc[0:2]# same, bu not recommended since not explicit

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."

In [13]:
movies.loc[:, ['title', 'duration']].head() #전체에서 title, duration까지 출력

                      title  duration
0  The Shawshank Redemption       142
1             The Godfather       175
2    The Godfather: Part II       200
3           The Dark Knight       152
4              Pulp Fiction       154

In [14]:
movies.loc[0:2, 'title': 'duration']

                      title content_rating  genre  duration
0  The Shawshank Redemption              R  Crime       142
1             The Godfather              R  Crime       175
2    The Godfather: Part II              R  Crime       200

In [ ]:
movies.head(3).drop(['star_rating','actors_list'], axis=1) #열삭제

                      title content_rating  genre  duration
0  The Shawshank Redemption              R  Crime       142
1             The Godfather              R  Crime       175
2    The Godfather: Part II              R  Crime       200

In [15]:
movies[movies.genre == 'Crime'].head()
#movies.loc[movies.genre == 'Crime', :].head()
#movies.loc[movies.genre == 'Crime']

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."

In [16]:
movies.loc[movies.genre == 'Crime', 'title'] # 장르가 crime인 것의 title가져오기
#movies.loc[movies.genre == 'Crime'].title

0      The Shawshank Redemption
1                 The Godfather
2        The Godfather: Part II
4                  Pulp Fiction
21                  City of God
                 ...
927                       Brick
931                Mean Streets
950                       Bound
969         Law Abiding Citizen
978                 Wall Street
Name: title, Length: 124, dtype: object

In [ ]:
# movies[movies.duration >= 200].genre
movies.loc[movies.duration >= 200,'genre'] # 기간이 200이상인 장르 가져오기기

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [ ]:
movies.iloc[:, [0,3]].head(3) # 열은 인덱스0,3

   star_rating  genre
0          9.3  Crime
1          9.2  Crime
2          9.1  Crime

In [17]:
movies.iloc[:, 0:4].head()  # loc과는 다름 4는 포함하지 않음

   star_rating                     title content_rating   genre
0          9.3  The Shawshank Redemption              R   Crime
1          9.2             The Godfather              R   Crime
2          9.1    The Godfather: Part II              R   Crime
3          9.0           The Dark Knight          PG-13  Action
4          8.9              Pulp Fiction              R   Crime

In [ ]:
movies[(movies.duration >= 200) & (movies.genre == 'Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [ ]:
(movies.duration >= 200) & (movies.genre == 'Drama')  # inside

0      False
1      False
2      False
3      False
4      False
       ...
974    False
975    False
976    False
977    False
978    False
Length: 979, dtype: bool